volumes:
  pgdata:
  redis_data:


networks:
  wh-network:
    driver: bridge

services:

  wh-nginx:
    image: nginx:1.25
    container_name: wh-nginx
    volumes:
      - ./cicd/nginx:/etc/nginx/
      - ./frontend/public:/usr/share/nginx/html/static
    ports:
      - 9000:80
    depends_on:
      - wh-backend
    networks:
      - wh-network

  wh-postgres:
    image: postgres:17.3-alpine
    container_name: wh-postgres
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - wh-network

  wh-redis:
    image: redis:7.2-alpine
    container_name: wh-redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    volumes:
      - 'redis_data:/bitnami/redis/data'
    networks:
      - wh-network

  wh-backend:
    container_name: wh-backend
    build:
      context: ./backend
      dockerfile: ../cicd/docker/backend/Dockerfile
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - backend/.env
    volumes:
      - ./backend:/srv/
    networks:
      - wh-network
    depends_on:
      - wh-postgres
      - wh-redis
    command: /bin/sh -c "./manage.py migrate && ./manage.py runserver 0.0.0.0:8000"
    # command:  /bin/sh -c "./manage.py migrate &&  uwsgi --master --http :8000 --module src.wsgi"
