# Generated by Django 5.1.6 on 2025-04-17 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnitGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coefficient', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='Коэфф. приведения')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='unit.unitgroup')),
            ],
            options={
                'verbose_name': 'Ед. измерений',
                'verbose_name_plural': 'Ед. измерений',
                'ordering': ['group', 'coefficient'],
            },
        ),
        migrations.CreateModel(
            name='UnitGroupTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(choices=[('ru', 'Русский'), ('en', 'English')], max_length=10, verbose_name='Языковая группа')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='unit.unitgroup', verbose_name='Группа ед. изм.')),
            ],
            options={
                'verbose_name': 'Перевод группы ед. измерений',
                'verbose_name_plural': 'Переводы групп ед. измерений',
                'ordering': ['group', 'language_code'],
            },
        ),
        migrations.CreateModel(
            name='UnitTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(choices=[('ru', 'Русский'), ('en', 'English')], max_length=10, verbose_name='Языковая группа')),
                ('title', models.CharField(max_length=100, verbose_name='Наименование')),
                ('short_title', models.CharField(max_length=20, verbose_name='Сокращенное наименование')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='unit.unit', verbose_name='Единица измерения')),
            ],
            options={
                'verbose_name': 'Перевод ед. измерений',
                'verbose_name_plural': 'Переводы ед. измерений',
                'ordering': ('unit', 'language_code'),
            },
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['group'], name='unit_unit_group_i_f8a9d8_idx'),
        ),
        migrations.AddIndex(
            model_name='unitgrouptranslation',
            index=models.Index(fields=['group', 'language_code'], name='unit_unitgr_group_i_6dcbd7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='unitgrouptranslation',
            unique_together={('group', 'language_code')},
        ),
        migrations.AddIndex(
            model_name='unittranslation',
            index=models.Index(fields=['unit', 'language_code'], name='unit_unittr_unit_id_1d3824_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='unittranslation',
            unique_together={('unit', 'language_code')},
        ),
    ]
