# Generated by Django 5.1.6 on 2025-04-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='unitgrouptranslation',
            index=models.Index(fields=['group'], name='unit_unitgr_group_i_ddbeae_idx'),
        ),
        migrations.AddIndex(
            model_name='unittranslation',
            index=models.Index(fields=['unit'], name='unit_unittr_unit_id_93182c_idx'),
        ),
    ]
